#!/data/data/com.termux/files/usr/bin/bash

export LD_PRELOAD=
export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/share/jdk8/lib/aarch64:/data/data/com.termux/files/usr/share/jdk8/lib/aarch64/jli:$LD_LIBRARY_PATH
umask 000
cd $HOME/ransomew4re/.data/binaries

java -Xmx1024m -jar /data/data/com.termux/files/home/ransomew4re/.data/binaries/signapk.jar /data/data/com.termux/files/home/ransomew4re/.data/binaries/publickey.x509.pem /data/data/com.termux/files/home/ransomew4re/.data/binaries/publickey.pk8 "$@" 

